#!/bin/bash

external_monitor=$(xrandr --query | grep 'HDMI-0')

if [[ $external_monitor = *connected* ]]; then
    xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal --output eDP-1-1 --mode 1920x1080 --rotate normal --right-of HDMI-0
fi
